# Site settings
title: Conférence agile frugale en ligne | Frug'Agile
description: Pour une conférence frugale virtuelle autour de l'agilité '!
keywords: agile, agilité, communauté agile, conférence agile en ligne, remote agile, frugalité
author: Association Frug'Agile
baseurl: "/"
url: "https://www.frugagile.org"

email: frugagilefrance@gmail.com

twitter_username: FrugAgile
linkedin_username: frug-agile
instagram_username: frugagile
youtube_username : UCs_dv4WVqg4MG7ZOhU-NPUQ
discord_id : Ga4kRWzq

title_en: Agile online and frugal conference agile | Frug'Agile
description_en: A frugal and virtual online conference to discuss about agile !
keywords_en: agile, agility, agile community, online conference, remote agile, frugality

# Build settings
markdown: kramdown
